spring:
  redis:
    host: localhost
    port: 6379
  cache:
    cache-names: days,months
#  autoconfigure:
#    exclude: io.microsamples.cache.admin.config.CacheAdminAutoConfiguration
management:
  security:
    enabled: false
cache:
  specs:
    days: 30
    months: 850

